### ISSUE TITLE
Some clarification questions

### ISSUE THREAD

**Issue by ttsesm** [Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io#1]
Hi,

Thank you for the nice dataset, I followed the instructions for downloading and decompressing it and this went smooth. I have some clarification questions though regarding the folder structure and format that I would appreciate if you could provide some feedback.

1. In the corresponding folder for each object in each subset you have a set of folders named either `fractured` or `mode`. Can you explain what is the difference if there is any?
2. Is there a known upper limit up to how many pieces each object is fractured or this is random each time?
3. Is there a way or some identification that gives the info or how to group the fractured pieces by their number as you are doing here https://breaking-bad-dataset.github.io/artifact.html or I would need to do that myself?
4. I've noticed that you can have multiple fractured pieces of the same amount e.g. split in pieces of 2 but what it changes is the way/position of where the object was fractured, is that correct?

Thanks.

**Comment by Wuziyi616** [comment]
Hi, thanks for your interest in our work! Most of the details are provided in our paper, which is still under review and not public yet. You can check back later for more information. I'll try to briefly answer your questions here:

1. You can think of them as the same. More precisely, mode are introduced in Silvia's paper (the fracture simulation program we use here), and fractures are generated from different modes. But in terms of assembly task, I think they're similar things
2. We did a rejection sampling of 2-100 pieces in the simulation code IIRC, so I think the upper limit is 100
3. No, you need to manually read them. But it's a good idea to provide such metadata. We'll look into this and maybe include in our next release
4. Yes you're right! Though the number of pieces are the same, the way they're breaking are different. Each fracture/mode folder is a unique way of breaking that object

**Comment by ttsesm** [comment]
Thanks.

**Comment by ttsesm** [comment]
Btw, I've created some metadata regarding the sampling and how many pieces each folder has for each object in each subset. In the .json files the `key` is number of fractures/samples and the values are the list with the folders that have that amount of fractures/samples. One .json file for each subset, in case that someone finds it useful.

[sampling_.zip](https://github.com/Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io/files/9039382/sampling_.zip)
