### ISSUE TITLE
Removing the internal geometry of the fractured mesh models

### ISSUE THREAD

**Issue by ttsesm** [Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io#2]
Hi,

I am using the downloaded files and I've noticed that there in the mesh models there are internal points and faces which are kind of redundant. Thus, I would like to know whether you are aware of any method that I could keep only the external mesh structure and remove the internal geometry i.e. points/faces.

Thanks.

**Comment by Wuziyi616** [comment]
Thanks for the follow-up question. As we are cleaning the dataset, we have indeed noticed some issues in the current pre-release version. We will take reviewers' questions and your questions into consideration. It's very likely that we'll have an official release later (maybe after the paper decision or so). Please understand that the current data is for review purposes. I believe there are still things to improve.

**Comment by ttsesm** [comment]
Sure, no worries ;-).
