### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by juhongm999** [Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io#3]
Dear authors,
Thanks for great work!
I would be truly appreciated if the evaluation code is publicly provided (to reproduce the results in Table 3 of the main paper).
Do you have any plan to release the code?

Thanks.

**Comment by Wuziyi616** [comment]
Hey, thanks for your interest in our work. Definitely yes! We plan to release the benchmark code upon the acceptance of the paper
