### ISSUE TITLE
Dependency missing to run decompress.py

### ISSUE THREAD

**Issue by regarry** [Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io#7]
Hi, 

I followed the readme but I was missing the python package "gpytoolbox" when I tried to run the decompress.py script. After running `pip install gpytoolbox`, I was able to run the script without error. I suggest adding the step `pip install gpytoolbox` to the install dependencies section of the readme.

Thank you,
Ryan

**Comment by Wuziyi616** [comment]
Thanks for the comment. I thought it's included but turns out it's not. Feel free to create a PR for this?

**Comment by ronaldpan** [comment]
When I run "pip install gpytoolbox", 
ERROR: Failed building wheel for gpytoolbox
Failed to build gpytoolbox
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (gpytoolbox)

pip install gpytoolbox==0.2.0 is OK.

**Comment by Wuziyi616** [comment]
I think 0.2.0 should be fine because it's released after the publication of Breaking Bad. I've added this in the README. Thanks
